### PR TITLE
Add match query boost

### PR DESCRIPTION
**Pull request by Cowa**
Issue #68

It follows this format: 

``` json
"match": {
  "content": {
    "query": "Elasticsearch",
    "boost": 3 
  }
}
```

https://www.elastic.co/guide/en/elasticsearch/guide/current/_boosting_query_clauses.html

### CODE REVIEW

**Comment by rcoh** [comment]
Great! Would you mind adding a test to https://github.com/SumoLogic/elasticsearch-client/blob/master/elasticsearch-core/src/test/scala/com/sumologic/elasticsearch/restlastic/RestlasticSearchClientTest.scala?

**Comment by Cowa** [comment]
Hi @rcoh, I added the test

**Comment by rcoh** [comment]
Looks good. One last thing: Would you mind unifying `MatchQuery` and `MatchQueryWithBoost` by adding a boost argument to match query but defaulting it to none, rather than adding a new class:

```
case class MatchQuery(key: String, value: String, boost: Option[Double]) {
   ...
}
```

**Comment by Cowa** [comment]
Thanks for the feedback!

By default ElasticSearch uses a boost of `1`. So we could have `boost: Double = 1` instead of `boost: Option[Double] = None`. What do you think? It will avoid the user to wrap boosts with `Some`.

**With `Option`**

``` scala
case class MatchQuery(key: String, value: String, boost: Option[Double] = None) extends Query {
    val _match = "match"
    val _query = "query"
    val _boost = "boost"

    override def toJson: Map[String, Any] = {
      Map(_match ->
        Map(key ->
          Map(_query -> value,
              _boost -> boost.getOrElse(1))))
    }
  }
```

**With `1` as default**

``` scala
case class MatchQuery(key: String, value: String, boost: Double = 1) extends Query {
    val _match = "match"
    val _query = "query"
    val _boost = "boost"

    override def toJson: Map[String, Any] = {
      Map(_match ->
        Map(key ->
          Map(_query -> value,
              _boost -> boost)))
    }
  }
```

**Comment by rcoh** [comment]
Default of 1 is much better! Thanks for the help.

**Comment by Cowa** [comment]
Perfect! I pushed the change.

**Review by rcoh — APPROVED** [review]
LGTM. Thanks for contributing!

**Comment by rcoh** [comment]
Closes #69

**Comment by Cowa** [comment]
You're welcome!

One last question, does the new release will be published on the maven repo soon?
I'll need it to deploy my application on production.

**Comment by rcoh** [comment]
@CCheSumo would you mind cutting a new release when you get a chance?

**Comment by CCheSumo** [comment]
Sure. I will do it shortly

**Comment by rcoh** [comment]
@Cowa the new version has been pushed to maven central

**Comment by Cowa** [comment]
Thank you! 👍

**Pull request merged**
