### PR TITLE
Make execution context an argument for ScrollClient methods that crea…

### PR DESCRIPTION
**Pull request by kumar-avijit**
…te a Future
This PR adds a new implicit argument to supply an `ExecutionContext` to all those `RestlasticSearchClient` methods which create a `Future`.

### CODE REVIEW

**Comment by williamleferrand** [comment]
lgtm!

**Comment by kumar-avijit** [comment]
@rcoh I would like to get your opinion on bumping up version number for this.

This is a backward incompatible change because it adds an extra parameter to various methods exposed by `ScrollClient` and `RestlasticSearchClient`. The options I see here are:
1. Bump up major version number. New version number would be `2.0.0`.
2. Bump up minor version number. New version number would be `1.1.0`.
3. (suggested as an option by @cddude229) Restore original API + add a variant for each method that takes in execution context. Bump up version number to `1.1.0`.

I am equally fine with Option 1 and 3, which are both complaint with Semantic Versioning. Option 2 isn't. 

#### Why not just add default value to the new parameter to restore backward compatibility?

It is possible to add defaults for all current methods except for one method in `RestlasticSearchClient`. The `bulkIndex` method there is already overloaded and does not admit default parameter values.

**Comment by rcoh** [comment]
another option would be to add a default parameter to the `RestlasticSearchClient` itself that provides the execution context

**Comment by kumar-avijit** [comment]
Ah yes, that's another option but it unfortunately falls short for our requirements atm, which is to be able to use different thread pools for indexing and searching.

**Comment by kumar-avijit** [comment]
I suppose, in that case, we could add 2 default parameters to `RestlasticSearchClient` to accommodate differentiating search thread pool from indexing thread pool.

**Pull request merged**
