### PR TITLE
update to akka 2.4.14

### PR DESCRIPTION
**Pull request by trbngr**

### CODE REVIEW

**Comment by rcoh** [comment]
The build is failing with
```
java.lang.UnsupportedClassVersionError: akka/actor/ActorSystem$ : Unsupported major.minor version 52.0
```

Does it pass locally for you?

**Comment by trbngr** [comment]
Yes. And I'm running it in production already ;)

It's caused by a JDK version mismatch. Your build server is running `java version "1.7.0_76"`. I bet JDK 8 would fix it right up.

https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/

**Comment by arun-rama** [comment]
👍

**Comment by rcoh** [comment]
Upgrade is now in progress. Closing this PR. The 2.0 client will support 2.12 / akka 2.4

**Pull request closed without merging**
